version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - tasker_network
    depends_on:
      - mongo
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@mongo:27017/tasker?authSource=admin


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=tasker
    volumes:
      - mongo-data:/data/db
    networks:
      - tasker_network

networks:
  tasker_network:
    driver: bridge

volumes:
  mongo-data: